/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type HeroBlockContent = Array<{
  children?: Array<
    | {
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }
    | {
        label?: string;
        _type: "agePlaceholder";
        _key: string;
      }
    | {
        label?: string;
        _type: "workplacePlaceholder";
        _key: string;
      }
  >;
  style?: "normal";
  listItem?: never;
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type Button = {
  _type: "button";
  text_en?: string;
  text_no?: string;
  link?: string;
  type?: "primary" | "secondary" | "outline" | "ghost";
  icon?: LucideIcon;
};

export type SkillReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "skill";
};

export type SkillCategory = {
  _id: string;
  _type: "skillCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name_en?: string;
  name_no?: string;
  slug?: Slug;
  skills?: Array<
    {
      _key: string;
    } & SkillReference
  >;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Skill = {
  _id: string;
  _type: "skill";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  url?: string;
  icon?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type WorkExperience = {
  _id: string;
  _type: "workExperience";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  company_en?: string;
  company_no?: string;
  position_en?: string;
  position_no?: string;
  description_en?: BlockContent;
  description_no?: BlockContent;
  period_en?: string;
  period_no?: string;
  startDate?: string;
  endDate?: string;
  companyUrl?: string;
  certificate?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  buttons?: Array<
    {
      _key: string;
    } & Button
  >;
};

export type ProjectReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "project";
};

export type Education = {
  _id: string;
  _type: "education";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  institution_en?: string;
  institution_no?: string;
  degree_en?: string;
  degree_no?: string;
  location_en?: string;
  location_no?: string;
  description_en?: BlockContent;
  description_no?: BlockContent;
  period_en?: string;
  period_no?: string;
  startDate?: string;
  endDate?: string;
  relatedProjects?: Array<
    {
      _key: string;
    } & ProjectReference
  >;
  externalUrl?: string;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title_en?: string;
  title_no?: string;
  slug?: Slug;
  projectType?: "featured" | "small";
  subtitle_en?: string;
  subtitle_no?: string;
  description_en?: BlockContent;
  description_no?: BlockContent;
  period_en?: string;
  period_no?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  imageAlt_en?: string;
  imageAlt_no?: string;
  buttons?: Array<
    {
      _key: string;
    } & Button
  >;
  link?: string;
  reportDocument?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  technologies?: Array<
    {
      _key: string;
    } & SkillReference
  >;
};

export type LucideIcon = string;

export type EducationReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "education";
};

export type WorkExperienceReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "workExperience";
};

export type SkillCategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "skillCategory";
};

export type Cv = {
  _id: string;
  _type: "cv";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  pageTitle_en?: string;
  pageTitle_no?: string;
  backButtonText_en?: string;
  backButtonText_no?: string;
  projectsSectionTitle_en?: string;
  projectsSectionTitle_no?: string;
  educationSectionTitle_en?: string;
  educationSectionTitle_no?: string;
  workSectionTitle_en?: string;
  workSectionTitle_no?: string;
  skillsSectionTitle_en?: string;
  skillsSectionTitle_no?: string;
  featuredProjects?: Array<
    {
      _key: string;
    } & ProjectReference
  >;
  education?: Array<
    {
      _key: string;
    } & EducationReference
  >;
  workExperience?: Array<
    {
      _key: string;
    } & WorkExperienceReference
  >;
  skillCategories?: Array<
    {
      _key: string;
    } & SkillCategoryReference
  >;
  contactText_en?: string;
  contactText_no?: string;
};

export type Frontpage = {
  _id: string;
  _type: "frontpage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroTitle_en?: string;
  heroTitle_no?: string;
  heroDescription_en?: HeroBlockContent;
  heroDescription_no?: HeroBlockContent;
  workplaceText_en?: string;
  workplaceText_no?: string;
  workplaceUrl?: string;
  portfolioTitle_en?: string;
  portfolioTitle_no?: string;
  featuredProjects?: Array<
    {
      _key: string;
    } & ProjectReference
  >;
  smallProjects?: Array<
    {
      _key: string;
    } & ProjectReference
  >;
  contactText_en?: string;
  contactText_no?: string;
  madeByText_en?: string;
  madeByText_no?: string;
  copiedNotification_en?: string;
  copiedNotification_no?: string;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  email?: string;
  birthDate?: string;
  githubUrl?: string;
  linkedinUrl?: string;
  cvProfileImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  contactText_en?: string;
  contactText_no?: string;
  madeByText_en?: string;
  madeByText_no?: string;
};

export type MediaTag = {
  _id: string;
  _type: "media.tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | HeroBlockContent
  | BlockContent
  | Button
  | SkillReference
  | SkillCategory
  | Slug
  | SanityImageAssetReference
  | Skill
  | SanityImageCrop
  | SanityImageHotspot
  | SanityFileAssetReference
  | WorkExperience
  | ProjectReference
  | Education
  | Project
  | LucideIcon
  | EducationReference
  | WorkExperienceReference
  | SkillCategoryReference
  | Cv
  | Frontpage
  | SiteSettings
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: ../src/lib/queries.ts
// Variable: siteSettingsQuery
// Query: *[_type == "siteSettings"][0] {    name,    email,    birthDate,    githubUrl,    linkedinUrl,    profileImage,    cvProfileImage,    logoImage,    contactText_en,    contactText_no,    madeByText_en,    madeByText_no  }
export type SiteSettingsQueryResult = {
  name: string | null;
  email: string | null;
  birthDate: string | null;
  githubUrl: string | null;
  linkedinUrl: string | null;
  profileImage: null;
  cvProfileImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  logoImage: null;
  contactText_en: string | null;
  contactText_no: string | null;
  madeByText_en: string | null;
  madeByText_no: string | null;
} | null;

// Source: ../src/lib/queries.ts
// Variable: frontpageQuery
// Query: *[_type == "frontpage"][0] {    heroTitle_en,    heroTitle_no,    heroDescription_en,    heroDescription_no,    workplaceText_en,    workplaceText_no,    workplaceUrl,    portfolioTitle_en,    portfolioTitle_no,    featuredProjects[]-> {      _id,      title_en,      title_no,      subtitle_en,      subtitle_no,      description_en,      description_no,      period_en,      period_no,      image,      imageAlt_en,      imageAlt_no,      buttons[] {        text_en,        text_no,        link,        type,        icon      }    },    smallProjects[]-> {      _id,      title_en,      title_no,      subtitle_en,      subtitle_no,      link    },    contactText_en,    contactText_no,    madeByText_en,    madeByText_no,    copiedNotification_en,    copiedNotification_no  }
export type FrontpageQueryResult = {
  heroTitle_en: string | null;
  heroTitle_no: string | null;
  heroDescription_en: HeroBlockContent | null;
  heroDescription_no: HeroBlockContent | null;
  workplaceText_en: string | null;
  workplaceText_no: string | null;
  workplaceUrl: string | null;
  portfolioTitle_en: string | null;
  portfolioTitle_no: string | null;
  featuredProjects: Array<{
    _id: string;
    title_en: string | null;
    title_no: string | null;
    subtitle_en: string | null;
    subtitle_no: string | null;
    description_en: BlockContent | null;
    description_no: BlockContent | null;
    period_en: string | null;
    period_no: string | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    imageAlt_en: string | null;
    imageAlt_no: string | null;
    buttons: Array<{
      text_en: string | null;
      text_no: string | null;
      link: string | null;
      type: "ghost" | "outline" | "primary" | "secondary" | null;
      icon: LucideIcon | null;
    }> | null;
  }> | null;
  smallProjects: Array<{
    _id: string;
    title_en: string | null;
    title_no: string | null;
    subtitle_en: string | null;
    subtitle_no: string | null;
    link: string | null;
  }> | null;
  contactText_en: string | null;
  contactText_no: string | null;
  madeByText_en: string | null;
  madeByText_no: string | null;
  copiedNotification_en: string | null;
  copiedNotification_no: string | null;
} | null;

// Source: ../src/lib/queries.ts
// Variable: cvPageQuery
// Query: *[_type == "cv"][0] {    pageTitle_en,    pageTitle_no,    backButtonText_en,    backButtonText_no,    projectsSectionTitle_en,    projectsSectionTitle_no,    educationSectionTitle_en,    educationSectionTitle_no,    workSectionTitle_en,    workSectionTitle_no,    skillsSectionTitle_en,    skillsSectionTitle_no,    featuredProjects[]-> {      _id,      title_en,      title_no,      description_en,      description_no,      period_en,      period_no,      buttons[] {        text_en,        text_no,        link,        type,        icon      },      "reportUrl": reportDocument.asset->url    },    education[]-> {      _id,      institution_en,      institution_no,      degree_en,      degree_no,      location_en,      location_no,      description_en,      description_no,      period_en,      period_no,      externalUrl,      relatedProjects[]-> {        _id,        title_en,        title_no,        link      }    },    workExperience[]-> {      _id,      company_en,      company_no,      position_en,      position_no,      description_en,      description_no,      period_en,      period_no,      companyUrl,      buttons[] {        text_en,        text_no,        link,        type,        icon      }    },    skillCategories[]-> {      _id,      name_en,      name_no,      skills[]-> {        _id,        name,        url,        icon      }    },    contactText_en,    contactText_no  }
export type CvPageQueryResult = {
  pageTitle_en: string | null;
  pageTitle_no: string | null;
  backButtonText_en: string | null;
  backButtonText_no: string | null;
  projectsSectionTitle_en: string | null;
  projectsSectionTitle_no: string | null;
  educationSectionTitle_en: string | null;
  educationSectionTitle_no: string | null;
  workSectionTitle_en: string | null;
  workSectionTitle_no: string | null;
  skillsSectionTitle_en: string | null;
  skillsSectionTitle_no: string | null;
  featuredProjects: Array<{
    _id: string;
    title_en: string | null;
    title_no: string | null;
    description_en: BlockContent | null;
    description_no: BlockContent | null;
    period_en: string | null;
    period_no: string | null;
    buttons: Array<{
      text_en: string | null;
      text_no: string | null;
      link: string | null;
      type: "ghost" | "outline" | "primary" | "secondary" | null;
      icon: LucideIcon | null;
    }> | null;
    reportUrl: string | null;
  }> | null;
  education: Array<{
    _id: string;
    institution_en: string | null;
    institution_no: string | null;
    degree_en: string | null;
    degree_no: string | null;
    location_en: string | null;
    location_no: string | null;
    description_en: BlockContent | null;
    description_no: BlockContent | null;
    period_en: string | null;
    period_no: string | null;
    externalUrl: string | null;
    relatedProjects: Array<{
      _id: string;
      title_en: string | null;
      title_no: string | null;
      link: string | null;
    }> | null;
  }> | null;
  workExperience: Array<{
    _id: string;
    company_en: string | null;
    company_no: string | null;
    position_en: string | null;
    position_no: string | null;
    description_en: BlockContent | null;
    description_no: BlockContent | null;
    period_en: string | null;
    period_no: string | null;
    companyUrl: string | null;
    buttons: Array<{
      text_en: string | null;
      text_no: string | null;
      link: string | null;
      type: "ghost" | "outline" | "primary" | "secondary" | null;
      icon: LucideIcon | null;
    }> | null;
  }> | null;
  skillCategories: Array<{
    _id: string;
    name_en: string | null;
    name_no: string | null;
    skills: Array<{
      _id: string;
      name: string | null;
      url: string | null;
      icon: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
    }> | null;
  }> | null;
  contactText_en: string | null;
  contactText_no: string | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "siteSettings"][0] {\n    name,\n    email,\n    birthDate,\n    githubUrl,\n    linkedinUrl,\n    profileImage,\n    cvProfileImage,\n    logoImage,\n    contactText_en,\n    contactText_no,\n    madeByText_en,\n    madeByText_no\n  }\n': SiteSettingsQueryResult;
    '\n  *[_type == "frontpage"][0] {\n    heroTitle_en,\n    heroTitle_no,\n    heroDescription_en,\n    heroDescription_no,\n    workplaceText_en,\n    workplaceText_no,\n    workplaceUrl,\n    portfolioTitle_en,\n    portfolioTitle_no,\n    featuredProjects[]-> {\n      _id,\n      title_en,\n      title_no,\n      subtitle_en,\n      subtitle_no,\n      description_en,\n      description_no,\n      period_en,\n      period_no,\n      image,\n      imageAlt_en,\n      imageAlt_no,\n      buttons[] {\n        text_en,\n        text_no,\n        link,\n        type,\n        icon\n      }\n    },\n    smallProjects[]-> {\n      _id,\n      title_en,\n      title_no,\n      subtitle_en,\n      subtitle_no,\n      link\n    },\n    contactText_en,\n    contactText_no,\n    madeByText_en,\n    madeByText_no,\n    copiedNotification_en,\n    copiedNotification_no\n  }\n': FrontpageQueryResult;
    '\n  *[_type == "cv"][0] {\n    pageTitle_en,\n    pageTitle_no,\n    backButtonText_en,\n    backButtonText_no,\n    projectsSectionTitle_en,\n    projectsSectionTitle_no,\n    educationSectionTitle_en,\n    educationSectionTitle_no,\n    workSectionTitle_en,\n    workSectionTitle_no,\n    skillsSectionTitle_en,\n    skillsSectionTitle_no,\n    featuredProjects[]-> {\n      _id,\n      title_en,\n      title_no,\n      description_en,\n      description_no,\n      period_en,\n      period_no,\n      buttons[] {\n        text_en,\n        text_no,\n        link,\n        type,\n        icon\n      },\n      "reportUrl": reportDocument.asset->url\n    },\n    education[]-> {\n      _id,\n      institution_en,\n      institution_no,\n      degree_en,\n      degree_no,\n      location_en,\n      location_no,\n      description_en,\n      description_no,\n      period_en,\n      period_no,\n      externalUrl,\n      relatedProjects[]-> {\n        _id,\n        title_en,\n        title_no,\n        link\n      }\n    },\n    workExperience[]-> {\n      _id,\n      company_en,\n      company_no,\n      position_en,\n      position_no,\n      description_en,\n      description_no,\n      period_en,\n      period_no,\n      companyUrl,\n      buttons[] {\n        text_en,\n        text_no,\n        link,\n        type,\n        icon\n      }\n    },\n    skillCategories[]-> {\n      _id,\n      name_en,\n      name_no,\n      skills[]-> {\n        _id,\n        name,\n        url,\n        icon\n      }\n    },\n    contactText_en,\n    contactText_no\n  }\n': CvPageQueryResult;
  }
}
